import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { sourcePromptFiles, supervisorPeers, supervisors } from "../config/env.js";

const promptsDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "prompts");

function runtimeBlock(seat) {
  if (seat.runtimeKind === "api-loop") {
    const steps = seat.toolStepLimit || 4;
    return [
      `You run as a direct API model with a small tool loop, **capped at ${steps} model requests total** for the turn.`,
      "Your peer tools are `ask_claude` / `ask_codex` / `ask_gemini`; when browser automation is",
      "enabled, use `browser_check` to delegate a Playwright browser task to a CLI peer; your durable",
      "memory tools are `memory_read`, `memory_search`, `memory_remember`, `memory_forget`, and",
      "`memory_update_summary`.",
      "Peer tools run **sequentially**, each peer answers **once**, and peers **cannot** consult further",
      "peers (non-recursive), but CLI peers receive enabled shared tools such as memory, docs, and",
      "Playwright. Spend the step budget deliberately: ask a peer only for a compact, self-contained",
      "one-shot answer.",
    ].join("\n");
  }
  return [
    "You run as a single CLI process for this turn, with PAL MCP peer servers and shared MCP tools",
    "attached. You can consult peers (clink for CLI peers, chat for the DeepSeek API peer), and use",
    "enabled shared tools such as memory, docs, and Playwright browser automation. The conversation is",
    "rebuilt from history each turn; there is no persistent agent state between turns. You may issue",
    "parallel peer/tool calls within this turn if your CLI supports it; the calls themselves are",
    "synchronous.",
  ].join("\n");
}

function peersBlock(seatId, strengths) {
  const peers = supervisorPeers[seatId] || [];
  if (!peers.length) return "- (no peers configured for this seat)";
  return peers.map((peer) => `- **${peer}** - ${strengths[peer] || "(no description)"}`).join("\n");
}

function render(template, seat, strengths) {
  const out = template
    .replace(/\{\{SELF_NAME\}\}/g, seat.selfName)
    .replace(/\{\{SELF_ID\}\}/g, seat.id)
    .replace(/\{\{RUNTIME_BLOCK\}\}/g, runtimeBlock(seat))
    .replace(/\{\{PEERS_BLOCK\}\}/g, peersBlock(seat.id, strengths));
  const leftover = out.match(/\{\{[^}]+\}\}/);
  if (leftover) throw new Error(`Unreplaced placeholder ${leftover[0]} in seat "${seat.id}"`);
  return out;
}

async function main() {
  const config = JSON.parse(await readFile(path.join(promptsDir, "seats.json"), "utf8"));
  if (!Array.isArray(config.seats) || !config.strengths) {
    throw new Error("seats.json must define { strengths, seats[] }");
  }
  const rawTemplate = await readFile(path.join(promptsDir, "seat.template.md"), "utf8");
  const template = rawTemplate.replace(/^<!--[\s\S]*?-->\r?\n/, "");
  const banner = "<!-- GENERATED by `npm run build:prompts` from seat.template.md + seats.json. Do not edit by hand. -->\n";

  for (const seat of config.seats) {
    if (!supervisors[seat.id]) throw new Error(`Seat "${seat.id}" is not a known supervisor in env.js`);
    if (!seat.selfName) throw new Error(`Seat "${seat.id}" is missing selfName`);
    const fileName = path.basename(sourcePromptFiles[seat.id]);
    const body = render(template, seat, config.strengths);
    await writeFile(path.join(promptsDir, fileName), `${banner}${body}`, "utf8");
    console.log(`generated prompts/${fileName}`);
  }
}

await main();
